-- Seed data for OKINNOVATION PE
-- Run with: wrangler d1 execute ok_db --remote --file=scripts/seed.sql

INSERT INTO products (id, name, description, price, category, image, featured, "order") VALUES
('prod_01', 'Bumper Delantero Off-Road', 'Bumper delantero fabricado en plancha de acero con tratamiento anticorrosion. Incluye soporte para barra LED, gancho de remolque y proteccion de faros. Disponible para Toyota Hilux, Ford Ranger, Mitsubishi L200, Nissan Frontier y mas modelos.', 'Cotizar', 'Bumpers', '/products/bumper.png', 1, 1),
('prod_02', 'Kit de Suspension Elevada', 'Kit completo de suspension lift para tu 4x4. Incluye amortiguadores de gas de alta gama, resortes reforzados y bujes poliuretano. Mejora la distancia al suelo y el rendimiento off-road de tu vehiculo.', 'Cotizar', 'Suspension', '/products/suspension.png', 1, 2),
('prod_03', 'Boveda y Trapecio de Techo', 'Boveda y trapecio de techo fabricados en acero o aluminio con tratamiento anticorrosion. Soporta hasta 150kg de carga. Incluye sistema de iluminacion LED integrada y compatible con portaequipajes universales.', 'Cotizar', 'Estructuras', '/products/techo.png', 1, 3),
('prod_04', 'Estribos Electricos y Fijos', 'Estribos electricos con motor retractil o fijos de acero inoxidable. Superficie antideslizante, soporta hasta 200kg por lado. Instalacion profesional incluida para todos los modelos de camionetas y SUVs.', 'Cotizar', 'Estribos', '/products/estribos.png', 0, 4),
('prod_05', 'Kit de Iluminacion LED', 'Barra LED curved de 42 pulgadas con 240W de potencia. Incluye luces de trabajo, faros auxiliares LED y luces posicionales. Certificacion IP68 resistente al agua y polvo. Luminosidad de 12000 lumenes.', 'Cotizar', 'Iluminacion', '/products/iluminacion.png', 1, 5),
('prod_06', 'Proteccion de Carter y Chasis', 'Placas de proteccion de carter, transmision y diferencial fabricadas en acero al carbono de 4mm de espesor. Protege los componentes vitales de tu vehiculo contra rocas, obstaculos y terreno accidentado.', 'Cotizar', 'Proteccion', '/products/proteccion.png', 0, 6),
('prod_07', 'Overfenders y Body Kit', 'Overfenders ensanchadores de guardafangos para un look mas agresivo. Fabricados en fibra de vidrio o ABS de alta resistencia. Disponible para Toyota Hilux, Ford Ranger, Mitsubishi L200, Jeep Wrangler y mas.', 'Cotizar', 'Estetica', '/products/overfender.png', 0, 7);
